name: Nim
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  nimble_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: "stable"
      - name: Build
        run: nimble build
      - name: Run tests
        run: nimble test
